import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sample Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Sample <a href="https://nextjs.org">Next.js</a> App!
        </h1>
        <p>🖥️💖☕ by <a href="https://github.com/warengonzaga">Waren Gonzaga</a></p>
      </main>
    </div>
  )
}
